//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Valve.VR
{
    using System;
    using UnityEngine;
    
    
    public class SteamVR_Input_ActionSet_default : Valve.VR.SteamVR_ActionSet
    {
        
        public virtual SteamVR_Action_Boolean InteractUI
        {
            get
            {
                return SteamVR_Actions.default_InteractUI;
            }
        }
        
        public virtual SteamVR_Action_Boolean Teleport
        {
            get
            {
                return SteamVR_Actions.default_Teleport;
            }
        }
        
        public virtual SteamVR_Action_Boolean GrabPinch
        {
            get
            {
                return SteamVR_Actions.default_GrabPinch;
            }
        }
        
        public virtual SteamVR_Action_Boolean GrabGrip
        {
            get
            {
                return SteamVR_Actions.default_GrabGrip;
            }
        }
        
        public virtual SteamVR_Action_Pose Pose
        {
            get
            {
                return SteamVR_Actions.default_Pose;
            }
        }
        
        public virtual SteamVR_Action_Skeleton SkeletonLeftHand
        {
            get
            {
                return SteamVR_Actions.default_SkeletonLeftHand;
            }
        }
        
        public virtual SteamVR_Action_Skeleton SkeletonRightHand
        {
            get
            {
                return SteamVR_Actions.default_SkeletonRightHand;
            }
        }
        
        public virtual SteamVR_Action_Single Squeeze
        {
            get
            {
                return SteamVR_Actions.default_Squeeze;
            }
        }
        
        public virtual SteamVR_Action_Boolean HeadsetOnHead
        {
            get
            {
                return SteamVR_Actions.default_HeadsetOnHead;
            }
        }
        
        public virtual SteamVR_Action_Boolean LeftMultiplyHand
        {
            get
            {
                return SteamVR_Actions.default_LeftMultiplyHand;
            }
        }
        
        public virtual SteamVR_Action_Boolean LeftHandSpacingWest
        {
            get
            {
                return SteamVR_Actions.default_LeftHandSpacingWest;
            }
        }
        
        public virtual SteamVR_Action_Boolean LeftHandSpacingEast
        {
            get
            {
                return SteamVR_Actions.default_LeftHandSpacingEast;
            }
        }
        
        public virtual SteamVR_Action_Boolean LeftDeleteHand
        {
            get
            {
                return SteamVR_Actions.default_LeftDeleteHand;
            }
        }
        
        public virtual SteamVR_Action_Boolean LeftHandSpacingNorth
        {
            get
            {
                return SteamVR_Actions.default_LeftHandSpacingNorth;
            }
        }
        
        public virtual SteamVR_Action_Boolean LeftHandSpacingSouth
        {
            get
            {
                return SteamVR_Actions.default_LeftHandSpacingSouth;
            }
        }
        
        public virtual SteamVR_Action_Boolean RightHandSpacingWest
        {
            get
            {
                return SteamVR_Actions.default_RightHandSpacingWest;
            }
        }
        
        public virtual SteamVR_Action_Boolean RightHandSpacingEast
        {
            get
            {
                return SteamVR_Actions.default_RightHandSpacingEast;
            }
        }
        
        public virtual SteamVR_Action_Boolean RightHandSpacingNorth
        {
            get
            {
                return SteamVR_Actions.default_RightHandSpacingNorth;
            }
        }
        
        public virtual SteamVR_Action_Boolean RightHandSpacingSouth
        {
            get
            {
                return SteamVR_Actions.default_RightHandSpacingSouth;
            }
        }
        
        public virtual SteamVR_Action_Boolean RightMultiplyHand
        {
            get
            {
                return SteamVR_Actions.default_RightMultiplyHand;
            }
        }
        
        public virtual SteamVR_Action_Boolean RightDeleteHand
        {
            get
            {
                return SteamVR_Actions.default_RightDeleteHand;
            }
        }
        
        public virtual SteamVR_Action_Boolean LeftSwitchDirection
        {
            get
            {
                return SteamVR_Actions.default_LeftSwitchDirection;
            }
        }
        
        public virtual SteamVR_Action_Boolean RightSwitchDirection
        {
            get
            {
                return SteamVR_Actions.default_RightSwitchDirection;
            }
        }
        
        public virtual SteamVR_Action_Vibration Haptic
        {
            get
            {
                return SteamVR_Actions.default_Haptic;
            }
        }
    }
}
